# Fastfile

default_platform(:ios)

platform :ios do
  desc "Deploy a new build to Firebase App Distribution"
  lane :beta do
    build_ios_app(
      scheme: "Runner",
    )

    firebase_app_distribution(
      app: "1:378040104990:ios:9624bfb9ba7987ec12d60f", # Replace with your Firebase App ID
      groups: "test-group-1", # Replace with the group name or email list
    )
  end
end
