default_platform(:android)

platform :android do
  desc "Deploy to Firebase App Distribution"
  lane :beta do
    build_android_app(
      task: "assembleRelease",
      build_type: "Release"
    )
    firebase_app_distribution(
      app: "1:378040104990:android:1991411b9c76072412d60f",
      testers: "anvita.kaushik@jombay.com",
      release_notes: "Describe what's new in this build",
      firebase_cli_path: "/usr/local/bin/firebase",
      token: ENV['FIREBASE_TOKEN']
    )
  end
end
