# fastlane/Fastfile

default_platform(:android) # or :android if you are working with an Android project


platform :android do
  desc "Distribute a new version to Firebase App Distribution"
  lane :distribute_to_firebase do
    # Build your app (if not already built)
    # gradle(
    #   task: "assembleRelease"
    # )

    # Distribute the app to Firebase App Distribution
    firebase_app_distribution(
      app: "1:378040104990:android:1991411b9c76072412d60f",
      testers: "anvita.kaushik@jombay.com", # List of testers' emails separated by commas
      release_notes: "Release notes for this version",
      groups: "beta-testers" # Optional: a group name in Firebase App Distribution
    )
  end
end
