name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Create Keystore file
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/demo-test.keystore

      - name: List Files in android/app Directory
        run: |
          ls -la android/app

      - name: Create Key Properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=demo-test" >> android/key.properties
          echo "storeFile=android/app/demo-test.keystore" >> android/key.properties

      - name: List Files in root
        run: |
          ls -la 
          cat key.properties

      - name: Build APK
        run: flutter build apk --release

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: setup fastlane
        run: gem install fastlane

      - name: Run Fastlane
        run: fastlane distribute
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
