name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  print_statement:
    runs-on: ubuntu-latest

    steps:
      - name: Print Statement Every 3 Seconds
        run: |
          #!/bin/bash
          end=$((SECONDS+30))
          while [ $SECONDS -lt $end ]; do
            echo "Taaaaaaaaaaaaaaaaaa"
            sleep 3
          done

  print_ptatement:
    runs-on: ubuntu-latest

    steps:
      - name: Print Statement Every 3 Seconds
        run: |
          #!/bin/bash
          end=$((SECONDS+30))
          while [ $SECONDS -lt $end ]; do
            echo "Tbbbbbbbbb"
            sleep 3
          done

  print_stotement:
    runs-on: ubuntu-latest

    steps:
      - name: Print Statement Every 3 Seconds
        run: |
          #!/bin/bash
          end=$((SECONDS+30))
          while [ $SECONDS -lt $end ]; do
            echo "Tccccccccc."
            sleep 3
          done

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.16.7'

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Create Keystore file
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/demotest.keystore


      - name: Create Key Properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=demo-test" >> android/key.properties
          echo "storeFile=demotest.keystore" >> android/key.properties

      - name: Build APK
        run: flutter build apk --release

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload APK to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token $FIREBASE_TOKEN \
            --groups "test-group-1"
