name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Create Keystore file
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/demotest.keystore

      - name: List Files in android/app Directory
        run: |
          ls -la android/app

      - name: Create Key Properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=demo-test" >> android/key.properties
          echo "storeFile=demotest.keystore" >> android/key.properties


      - name: Build APK
        run: flutter build apk --release


      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase login:ci --token $FIREBASE_TOKEN

      - name: Upload APK to Firebase
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --token $FIREBASE_TOKEN \
            --groups "test-group-1"
