name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.3.4'

      - name: install firebase tool
        run: |
          yarn global add firebase-tools
          echo "::add-path::$(yarn global bin)"

      - name: setup fastlane
        run: bundle install

      - name: distribute to firebase
        run: bundle exec fastlane android firebase_distribution
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
